module.exports = {
  parser: "@typescript-eslint/parser",
  extends: [
    "plugin:@typescript-eslint/recommended",
    "plugin:import/typescript",
    "prettier",
  ],
  plugins: ["import", "react", "react-hooks"],
  rules: {
    "@typescript-eslint/consistent-type-definitions": "error",
    "@typescript-eslint/consistent-type-imports": "error",
    "@typescript-eslint/explicit-module-boundary-types": "off",
    "@typescript-eslint/no-unused-vars": "error",
    "@typescript-eslint/no-use-before-define": "off",
    "array-callback-return": "error",
    eqeqeq: ["error", "always"],
    "import/export": "warn",
    "import/no-unused-modules": ["error", { unusedExports: true }],
    "import/order": [
      "error",
      {
        groups: ["builtin", "external", "sibling", "parent", "index"],
        "newlines-between": "always",
      },
    ],
    "import/no-anonymous-default-export": "error",
    "no-else-return": ["error", { allowElseIf: false }],
    "no-redeclare": "error",
    "no-use-before-define": "off",
    "prefer-const": "error",
    "prefer-template": "error",
    "react-hooks/exhaustive-deps": "error",
    "react/jsx-boolean-value": "error",
    "react/jsx-curly-brace-presence": "error",
    "react/jsx-key": "error",
    "react/jsx-pascal-case": "error",
    "no-unreachable": "error",
    "prettier/prettier": "error",
  },
};
